compressionLevel: mixed

enableGlobalCache: false

npmMinimalAgeGate: 1440

nodeLinker: node-modules

packageExtensions:
  "@lexical/react@*":
    peerDependencies:
      yjs: ">=13.5.22"
  "@mdxeditor/editor@*":
    peerDependencies:
      "@codemirror/language": "^6.0.0"
      "@lezer/highlight": "^1.0.0"
      yjs: ">=13.5.22"
